# Site settings
author: Eyerusalem Kebede
title: Coding Journey
header-img: img/home-bg.png
email: 3yerus@gmail.com
copyright_name: Eyerusalem Kebede
description: > # this means to ignore newlines until "baseurl:"
  my coding journey..
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Eyeruz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
